### ISSUE TITLE
PHP 8 Deprecation: Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by caseydwyer** [lukapeharda/tailwindcss-color-palette-generator#2]
Hi there,

I'm hitting the following error, when trying to run `getHex()` on a Color. Latest version of the package + PHP v8.0.11:

`PHP Deprecated:  Implicit conversion from float 0.5759627129540341 to int loses precision in A:\laragon\www\twenty-for\vendor\lukapeharda\tailwindcss-color-palette-generator\src\Color.php on line 234`

Here's the method & hexcode I'm running:
```php
$paletteGenerator = new PaletteGenerator;
$paletteGenerator->setBaseColor( Color::fromHex('007a33') );
return $paletteGenerator->getPalette();
```

Thanks for building this package! Handy concept, if I'm able to get it working. Let me know if there's anything else I can provide or help with, here.

**Comment by lukapeharda** [comment]
Hi @caseydwyer,

thank you for reporting the issue. Latest version (0.3.2) should get rid of the deprecation notice.

Kind regards,
Luka Peharda
